site_name: Moonshot
repo_url: https://github.com/moonshot-admin/moonshot

plugins:
  - search
  - mkdocstrings
  - swagger-ui-tag:
        defaultModelsExpandDepth: -1
        docExpansion: none

theme:
  features:
      - navigation.footer
      - navigation.top
      - toc.integrate
      - toc.follow

  name: material
  locale: en
  include_sidebar: false

markdown_extensions:
  - markdown.extensions.extra
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list

nav: 
  - Home: index.md
  - Getting Started: 
    - Overview: getting_started/overview.md
    - Quick Install: getting_started/quick_install.md
    - Your First Test: getting_started/first_test.md
  - Tutorials:
    - Web UI: 
      - How to Create Custom Cookbook: tutorial/web-ui/create_cookbook.md
      - How to Create Connector Endpoint: tutorial/web-ui/create_endpoint.md
      - How to Run Benchmark Tests: tutorial/web-ui/benchmark.md
      - How to Run Red Teaming: tutorial/web-ui/redteam.md
    - CLI : 
      - How to Create Custom Benchmark Tests: tutorial/cli/create_benchmark_tests.md
      - How to Create Connector Endpoint: tutorial/cli/create_endpoint.md
      - How to Run Benchmark Tests: tutorial/cli/run_benchmark_tests.md
      - How to Run Red Teaming: tutorial/cli/run_red_teaming.md
  - User Guide: 
    - Web API:
      - Get Started with Web API : web_api/web_api_guide.md
      - Connector Endpoints: web_api/connector_endpoints.md
      - Cookbook Endpoints: web_api/cookbook_endpoints.md
      - Recipe Endpoints: web_api/recipe_endpoints.md
      - Session Endpoints: web_api/sessions_endpoints.md
      - Prompt Template Endpoints: web_api/prompt_template_endpoints.md
    - CLI: 
      - Get Started with CLIs : cli/cli_guide.md
      - Connecting to LLMs: cli/connecting_endpoints.md
      - Running Benchmark: cli/benchmarking.md
      - Running Red Teaming: cli/red_teaming.md
    - Moonshot UI User Guide: 
      - Get Started with Web UI: web_ui/web_ui_guide.md
      - Model Endpoints: web_ui/model_endpoint.md
      - Running Benchmark: web_ui/run_benchmark_test.md
      - Cookbook: web_ui/cookbook.md
      - Red Teaming: web_ui/red_teaming.md
    - CLI: 
      - Connecting to LLMs: cli/connecting_endpoints.md
      - Running Benchmark: cli/benchmarking.md
      - Running Red Teaming: cli/red_teaming.md 
      - Adding Your Own Tests: cli/add_your_own_tests.md
  - API Reference:
    - Moonshot Library:
        - Connector Endpoint API: api_reference/api_connector_endpoint.md
        - Connector API: api_reference/api_connector.md
        - Context Strategy API: api_reference/api_context_strategy.md
        - Cookbook API: api_reference/api_cookbook.md
        - Dataset API: api_reference/api_dataset.md
        - Environment Variable API: api_reference/api_environment_variables.md
        - Metric API: api_reference/api_metrics.md
        - Prompt Template API: api_reference/api_prompt_template.md
        - Recipe API: api_reference/api_recipe.md
        - Red Teaming API: api_reference/api_red_teaming.md
        - Result API: api_reference/api_result.md
        - Run API: api_reference/api_run.md
        - Runner API: api_reference/api_runner.md
        - Session API: api_reference/api_session.md
    - Web-API: api_reference/web_api_swagger.md
  - Advance User:
    - How to Create a Metric: a.py
    - How to Create a Moonshot-Compatible Dataset : a.py 
    - How to Create an Attack Module : ok.py
    - How to Create a Prompt Template: a.py
    - How to Create a Connector : a-py
  - Resources:
      - Jupyter Notebook: resources/jupyter_notebook.md
      - Cookbook: resources/cookbooks.md
      - Recipes: resources/recipes.md
      - Datasets: resources/datasets.md
      - Metrics: resources/metrics.md

  - Troubleshoot : troubleshoot/troubleshoot.md