site_name: Moonshot
repo_url: https://github.com/moonshot-admin/moonshot

plugins:
  - search
  - mkdocstrings
  - swagger-ui-tag:
        defaultModelsExpandDepth: -1
        docExpansion: none

extra_css:
  - stylesheets/custom_style.css

theme:
  features:
      - navigation.sections
      - navigation.indexes
      - navigation.footer
      - navigation.top
  
  name: material
  locale: en
  include_sidebar: false

markdown_extensions:
  - markdown.extensions.extra
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list

nav: 
  - Home: index.md
  - Getting Started: 
    - Overview: getting_started/overview.md
    - Quick Install: getting_started/quick_install.md
    - Your First Test: getting_started/first_test.md
  - Tutorials:
    - How To Create Custom Cookbook: tutorial/create_cookbook.md
    - How To Create Connector Endpoint: tutorial/create_endpoint.md
  - User Guide: 
    - Web UI Guide: 
      - Get Started with Web UI: web_ui/web_ui_guide.md
      - Model Endpoints: web_ui/model_endpoint.md
      - Running Benchmark: web_ui/run_benchmark_test.md
      - Cookbook: web_ui/cookbook.md
      - Red Teaming: web_ui/red_teaming.md
  - API Reference:
    - Moonshot Library:
        - Connector Endpoint API: understanding_moonshot/api_connector_endpoint.md
        - Connector API: understanding_moonshot/api_connector.md
        - Context Strategy API: understanding_moonshot/api_context_strategy.md
        - Cookbook API: understanding_moonshot/api_cookbook.md
        - Dataset API: understanding_moonshot/api_dataset.md
        - Environment Variable API: understanding_moonshot/api_environment_variables.md
        - Metric API: understanding_moonshot/api_metrics.md
        - Prompt Template API: understanding_moonshot/api_prompt_template.md
        - Recipe API: understanding_moonshot/api_recipe.md
        - Red Teaming API: understanding_moonshot/api_red_teaming.md
        - Result API: understanding_moonshot/api_result.md
        - Run API: understanding_moonshot/api_run.md
        - Runner API: understanding_moonshot/api_runner.md
        - Session API: understanding_moonshot/api_session.md
    - Web-API:
      - Web API Swagger: understanding_moonshot/web_api_swagger.md
  - Troubleshoot : troubleshoot/troubleshoot.md