site_name: Moonshot
repo_url: https://github.com/aiverify-foundation/moonshot

plugins:
  - search
  - mkdocstrings
  - swagger-ui-tag:
        defaultModelsExpandDepth: -1
        docExpansion: none

theme:
  features:
      - navigation.footer
      - navigation.top
      - toc.integrate
      - toc.follow

  name: material
  locale: en
  include_sidebar: false

markdown_extensions:
  - markdown.extensions.extra
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list

nav: 
  - Home: index.md
  - Getting Started: 
    - Overview: getting_started/overview.md
    - Quick Install: getting_started/quick_install.md
    - Your First Test: getting_started/first_test.md
  - Tutorials:
    - Web UI: 
      - How to Create Custom Cookbook: tutorial/web-ui/create_cookbook.md
      - How to Create Connector Endpoint: tutorial/web-ui/create_endpoint.md
      - How to Run Benchmark Tests: tutorial/web-ui/benchmark.md
      - How to Run Red Teaming: tutorial/web-ui/redteam.md
    - CLI : 
      - How to Create Custom Benchmark Tests: tutorial/cli/create_benchmark_tests.md
      - How to Create Connector Endpoint: tutorial/cli/create_endpoint.md
      - How to Run Benchmark Tests: tutorial/cli/run_benchmark_tests.md
      - How to Run Red Teaming: tutorial/cli/run_red_teaming.md
    - Contributor:
      - Configuring Moonshot WebAPI : contributor_guide/configure_web_api.md
      - How to Create a Connector : contributor_guide/create_connector.md
      - How to Create a Moonshot-Compatible Dataset (Coming soon!): never.md
      - How to Create an Attack Module (Coming soon!) : gonna.md
      - How to Create a Metric (Coming soon!): give.md
      - How to Create a Prompt Template (Coming soon!): you.md
      - How to Create a Context Strategy (Coming soon!): up.md
  - User Guide: 
    - Moonshot Web UI: 
      - Get Started with Moonshot Web UI: web_ui/web_ui_guide.md
      - Home: web_ui/homepage.md
      - Endpoint: web_ui/endpoint.md
      - Benchmarking: web_ui/benchmarking.md
      - Redteaming: web_ui/redteaming.md
      - History: web_ui/history.md
      - Utils: web_ui/utils.md
      - Choosing Relevant Tests: web_ui/choosing_relevant_tests.md
      - Connecting to LLMs: web_ui/connecting_to_llms.md
      - Running Benchmarks: web_ui/running_benchmarks.md
      - Red Teaming: web_ui/red_teaming.md
      - Creating Custom Cookbooks: web_ui/creating_custom_cookbooks.md
    - CLI: 
      - Connecting to LLMs: cli/connecting_endpoints.md
      - Running Benchmark: cli/benchmarking.md
      - Running Red Teaming: cli/red_teaming.md 
      - Adding Your Own Tests: cli/add_your_own_tests.md
  - API Reference:
    - Moonshot Library:
        - Connector Endpoint API: api_reference/api_connector_endpoint.md
        - Connector API: api_reference/api_connector.md
        - Context Strategy API: api_reference/api_context_strategy.md
        - Cookbook API: api_reference/api_cookbook.md
        - Dataset API: api_reference/api_dataset.md
        - Environment Variable API: api_reference/api_environment_variables.md
        - Metric API: api_reference/api_metrics.md
        - Prompt Template API: api_reference/api_prompt_template.md
        - Recipe API: api_reference/api_recipe.md
        - Red Teaming API: api_reference/api_red_teaming.md
        - Result API: api_reference/api_result.md
        - Run API: api_reference/api_run.md
        - Runner API: api_reference/api_runner.md
        - Session API: api_reference/api_session.md
    - Web-API: api_reference/web_api_swagger.md
  - Resources:
      - Jupyter Notebook: resources/jupyter_notebook.md
      - Cookbook: resources/cookbooks.md
      - Recipes: resources/recipes.md
      - Datasets: resources/datasets.md
      - Metrics: resources/metrics.md
      - Attack Modules: resources/attack_modules.md

  - Troubleshoot : troubleshoot/troubleshoot.md