[build-system]
requires = ["hatchling","hatch-build-scripts"]
build-backend = "hatchling.build"

[project]
name = "projectmoonshot-imda"
version = "0.3.4"
authors = [
    { name="The Moonshot Team", email="our.moonshot.team@gmail.com" }
]
description = "A simple and modular tool to evaluate and red-team any LLM application."
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: Apache Software License"
]
dependencies = [
    "python-slugify==8.0.4",
    "python-dotenv==1.0.1",
    "ijson==3.2.3",
    "jinja2==3.1.4",
    "pydantic==2.7.1",
    "pyparsing==3.1.2"
]

[project.optional-dependencies]
web-api = [
    "typing-extensions==4.11.0",
    "fastapi==0.110.3",
    "uvicorn==0.29.0",
    "dependency-injector==4.41.0",
]
cli = [
    "cmd2==2.4.3",
    "rich==13.7.1",
]
all = [
    "projectmoonshot-imda[web-api]",
    "projectmoonshot-imda[cli]",
]

[tool.hatch.build.targets.sdist]
artifacts = [
    "moonshot/data/connectors-endpoints/test-openai-endpoint.json"
]
exclude = [
  "docs/",
  "examples/",
  "misc/",
  "poetry.lock",
  "tests/",
]

[tool.hatch.build.targets.wheel]
packages = ["moonshot"]
artifacts = [
    "moonshot/data/connectors-endpoints/test-openai-endpoint.json"
]
exclude = [
  "docs/",
  "examples/",
  "misc/",
  "poetry.lock",
  "tests/",
]


[project.urls]
Repository = "https://github.com/moonshot-admin/moonshot"
Documentation = "https://moonshot-admin.github.io/moonshot/"
Issues = "https://github.com/moonshot-admin/moonshot/issues"

[tool.hatch.metadata]
allow-direct-references = true

[tool.poetry]
name = "projectmoonshot-imda"
version = "0.3.4"
description = "A simple and modular tool to evaluate and red-team any LLM application."
authors = ["The Moonshot Team <our.moonshot.team@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
python-slugify = "8.0.4"
python-dotenv = "1.0.1"
ijson = "3.2.3"
jinja2 = "3.1.4"
pydantic = "2.7.1"
pyparsing = "3.1.2"
typing-extensions = "4.11.0"
fastapi = "0.110.3"
uvicorn = "0.29.0"
dependency-injector = "4.41.0"
cmd2 = "2.4.3"
rich = "13.7.1"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
isort = "^5.13.2"
pre-commit = "^3.7.0"
pytest = "^8.2.0"
coverage = "^7.5.0"
pytest-mock = "^3.14.0"
flake8 = "^7.0.0"
poetry-plugin-export = "^1.7.1"
pyinstrument = "^4.6.2"
