log:
  level: "DEBUG"
  format: "[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"
  log_file_path: "web_api/log/web_api.log"
  log_file_max_size: 5242880
  log_file_backup_count: 3

asyncio:
  monitor_task: true

