
name: Nightly Build

on:

  # Run this workflow manually from Actions tab
  workflow_dispatch:
    inputs:
      branch_to_test:
        description: 'Branch or tag to build'
        required: true
        default: 'dev_main'
        type: string

# Allow one concurrent deployment
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  nightly-build:

    runs-on: ubuntu-latest
    timeout-minutes: 40
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-southeast-1

      - name: S3 test
        run: |
          aws s3 ls ${{ vars.AWS_S3_PATH }}
          echo "This job's status is ${{ job.status }}."

      # Deploy moonshot

      - name: Backup current install
        run: |
          command_id=$(aws ssm send-command \
            --instance-ids "${{ vars.AWS_SIT_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Backup current install" \
            --parameters 'commands=["sudo su - ubuntu -c \". ~/scripts/create_backup.sh\""]' \
            --query "Command.CommandId" \
            --output text)
          aws ssm wait command-executed \
            --command-id "$command_id" \
            --instance-id "${{ vars.AWS_SIT_INSTANCE_ID }}"
          status=$(aws ssm list-command-invocations \
            --command-id "$command_id" \
            --details \
            --query "CommandInvocations[0].Status" \
            --output text)
          echo "Command status: $status"

      - name: Install moonshot
        timeout-minutes: 30
        run: |
          command_id=$(aws ssm send-command \
            --instance-ids "${{ vars.AWS_SIT_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Install moonshot" \
            --parameters 'commands=["sudo su - ubuntu -c \". ~/scripts/install_ms_service.sh\""]' \
            --query "Command.CommandId" \
            --output text)
      
          max_attempts=100
          delay=60
          attempts=0
      
          while [ $attempts -lt $max_attempts ]; do
            status=$(aws ssm list-command-invocations \
              --command-id "$command_id" \
              --instance-id "${{ vars.AWS_SIT_INSTANCE_ID }}" \
              --query "CommandInvocations[0].Status" \
              --output text)
      
            if [ "$status" == "Success" ]; then
              echo "Command status: $status"
              exit 0
            elif [ "$status" == "InProgress" ]; then
              echo "Command status: $status, waiting..."
              sleep $delay
              attempts=$((attempts + 1))
            else
              echo "Command status: $status"
              exit 1
            fi
          done
      
          echo "Max attempts reached, exiting."
          exit 1

#      - name: Install moonshot
#        timeout-minutes: 30
#        run: |
#          command_id=$(aws ssm send-command \
#            --instance-ids "${{ vars.AWS_SIT_INSTANCE_ID }}" \
#            --document-name "AWS-RunShellScript" \
#            --comment "Install moonshot" \
#            --parameters 'commands=["sudo su - ubuntu -c \". ~/scripts/install_ms_service.sh\""]' \
#            --query "Command.CommandId" \
#            --output text)
#          aws ssm wait command-executed \
#            --command-id "$command_id" \
#            --instance-id "${{ vars.AWS_SIT_INSTANCE_ID }}"
#            --max-attempts 100 \
#            --delay 60
#          status=$(aws ssm list-command-invocations \
#            --command-id "$command_id" \
#            --details \
#            --query "CommandInvocations[0].Status" \
#            --output text)
#          echo "Command status: $status"
